spring:
  application:
    name: flood-web
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://flood-db.c9c2a686ayrx.us-east-1.rds.amazonaws.com:3306/flood_db
    username: juan_root
    password: 1152466831
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    jpa:
      repositories:
        enabled: true
    redis:
      host: flood-ro.g9b4ka.ng.0001.use1.cache.amazonaws.com
      port: 6379
      database: 0
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  thymeleaf:
    suffix: .html
    mode: HTML
    cache: false

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

twilio:
  account:
    sid: ACee31bdf233c34fae681ba3a65fc3ed1c
    auth-token: e1397bb390fec76c19e569c07900b717
  phone:
    number: +13158126244

