spring:
  application:
    name: flood-web

  datasource:
    url: jdbc:mysql://flood-db.c9c2a686ayrx.us-east-1.rds.amazonaws.com:3306/flood_db
    username: juan_root
    password: 1152466831
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    jpa:
      repositories:
        enabled: true

  thymeleaf:
    suffix: .html
    mode: HTML
    cache: false

  resources:
    static-locations: classpath:/static/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

